<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG5vfmkf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG5vfmkf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG5vfmkf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG5vfmkf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG5vfmkf\App_KernelDevDebugContainer([
    'container.build_hash' => 'G5vfmkf',
    'container.build_id' => 'f7612dc1',
    'container.build_time' => 1661916012,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG5vfmkf');
