<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXOeFkYE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXOeFkYE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXOeFkYE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXOeFkYE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXOeFkYE\App_KernelDevDebugContainer([
    'container.build_hash' => 'XOeFkYE',
    'container.build_id' => 'fe5620ac',
    'container.build_time' => 1661917413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXOeFkYE');
