<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], [], []],
    'app_facturador_dashboard' => [[], ['_controller' => 'App\\Controller\\FacturaController::dashboardFacturador'], [], [['text', '/facturador/dashboard']], [], [], []],
    'app_factura_crear' => [['id'], ['_controller' => 'App\\Controller\\FacturaController::crearFactura'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/facturador/generar/factura']], [], [], []],
    'app_gerente_dashboard' => [[], ['_controller' => 'App\\Controller\\FacturaController::dashboardGerente'], [], [['text', '/gerente/dashboard']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/registrar']], [], [], []],
    'app_cliente_dashboard' => [[], ['_controller' => 'App\\Controller\\TicketController::dashboardCliente'], [], [['text', '/cliente/dashboard']], [], [], []],
    'app_ticket_crear' => [[], ['_controller' => 'App\\Controller\\TicketController::crearTicket'], [], [['text', '/cliente/crear/ticket']], [], [], []],
    'app_tecnico_dashboard' => [[], ['_controller' => 'App\\Controller\\TicketController::dashboardTecnico'], [], [['text', '/tecnico/dashboard']], [], [], []],
    'app_ticket_atender' => [['id'], ['_controller' => 'App\\Controller\\TicketController::atenderTicket'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tecnico/atender/ticket']], [], [], []],
];
